### ISSUE TITLE
dnscrypt-proxy-openrc

### ISSUE THREAD

**Issue by physkets** [artix-linux/galaxy#28]
https://gitweb.gentoo.org/repo/gentoo.git/tree/net-dns/dnscrypt-proxy/files

**Comment by DamnWidget** [comment]
Can you please elaborate?

**Comment by thefallenrat** [comment]
`dnscrypt-proxy-openrc` were already availabe in testing for quite some time ago (5e8f8182eed8dc0860d61fea1754b020827f7767) and recently the package has been pushed to stable. 

As for the initscripts. Both of `confd` and `initd` files were sourced from gentoo repository.

https://github.com/artix-linux/galaxy/blob/dbb77fe9fe70637c259c73cfb142a0373750ec84/openrc-galaxy/PKGBUILD#L60

https://github.com/artix-linux/galaxy/blob/dbb77fe9fe70637c259c73cfb142a0373750ec84/openrc-galaxy/PKGBUILD#L135-L136

Because I think this issue is more like a feature request and the request were already fulfilled, I will close this. Feel free to open this if your intentions were otherwise

**Comment by physkets** [comment]
When I start the service, I get the following message:

```
$ sudo rc-service dnscrypt-proxy start
chown: invalid group: ‘dnscrypt:dnscrypt’
chown: invalid group: ‘dnscrypt:dnscrypt’
 * Starting dnscrypt-proxy ...                                                                                                                                                  [ ok ]
```

So should the relevant group and user be created upon install?
